### ISSUE TITLE
[initial] 프로젝트 기초세팅

### ISSUE THREAD

**Issue by stellar-halo** [Team-Sopetit/Sopetit-Android#1]
## 🛠️ ISSUE
- 프로젝트 기초 세팅

## 📑 To-Do
- [x] git ignore 설정
- [x] gradle 기초세팅
- [x] themes 기초 세팅
(툴바 제거 / 다크 모드 막기 / font padding 비활성화)
- [x]  app 기초세팅
(바인딩 액티비티/프래그먼트/util 함수/manifest에 인터넷 권한, 트래픽/화면회전 막기/application추가)
- [x] data 기초세팅
- [x] di 기초세팅(hilt)
- [x] 리뷰 후 머지 가능하게 하기 (protect branch)
- [x] 팀 추가
- [x] ci 추가
