### ISSUE TITLE
[ui] 행복루틴 - 추가하기(목록)

### ISSUE THREAD

**Issue by pump9918** [Team-Sopetit/Sopetit-Android#10]
## 🛠️ ISSUE
- 행복루틴 추가하기(목록)

## 📑 To-Do
- [x] chip으로 상단 카테고리 구성
- [x] 하단 카테고리 RecyclerView로 구성
- [x] 하단 카테고리 item 하나가 전체의 버튼
- [x] mockList사용 어댑터, 뷰홀더
- [x] 아이템 데코레이션으로 정렬 배치
- [x] 칩 클릭 시 다른 리스트 불러오기
