### ISSUE TITLE
[fix] 행복루틴 QA 이슈 해결

### ISSUE THREAD

**Issue by pump9918** [Team-Sopetit/Sopetit-Android#101]
## 🛠️ ISSUE
- 자잘한 QA 이슈 해결

## 📑 To-Do
- [x] 카드 규격이 약간 안맞음(HappyDetailActivity)
- [x] HappyDetailActivity의 바텀시트 이미지가 틀림
- [x] HappyListActivity 위 item에 기본 이미지 넣기
- [x] 뒤로가기 터치 영역 늘리기
- [x] 전체 버튼 디폴트로 눌려있게
