### ISSUE TITLE
[fix] 버튼 터치영역 수정 및 웹사이트 연결

### ISSUE THREAD

**Issue by minemi00** [Team-Sopetit/Sopetit-Android#110]
## 🛠️ ISSUE
- 모든 뷰 터치영역 수정

## 📑 To-Do
- [ ] 모든 뷰 뒤로가기 버튼 터치영역 넓히기
- [ ] 홈뷰 설정버튼, 결제창 버튼 터치영역 수정
- [ ] 편집 라디오버튼 터치영역 수정
