### ISSUE TITLE
[fix] 데일리 루틴 추가하기 qa

### ISSUE THREAD

**Issue by minemi00** [Team-Sopetit/Sopetit-Android#113]
## 🛠️ ISSUE
- 데일리 루틴 추가하기 뷰 qa

## 📑 To-Do
- [ ] 카드뷰에 글자들 패딩 적용하기
- [ ] 카드뷰 둥글게 하기
- [ ] 테마 앞에 마진값 주기
