### ISSUE TITLE
[fix] 전체 1차 qa 자잘자잘 이슈

### ISSUE THREAD

**Issue by minemi00** [Team-Sopetit/Sopetit-Android#125]
## 🛠️ ISSUE
- 전체 1차 qa 자잘자잘 이슈

## 📑 To-Do
- [x] 이름 글자색 수정하기
- [x] 설정에서 상단바와 컨텐츠 간격 줄이기
- [x] 연타해야 하는 부분 클릭리스너 바꾸기
