### ISSUE TITLE
[fix] 릴리즈 전 데일리 루틴 이슈 수정

### ISSUE THREAD

**Issue by minemi00** [Team-Sopetit/Sopetit-Android#136]
## 🛠️ ISSUE
- 최종 릴리즈 전 이슈 수정

## 📑 To-Do
- [x] 스낵바 위치 조정, 띄워져있는 시간 짧게
- [x] 엠티이미지로 placeholder 이용해서 갈아 끼워주기
- [x] 뷰페이저 좌우 삭제하기
