### ISSUE TITLE
[fix] 릴리즈 전 QA 이슈 수정

### ISSUE THREAD

**Issue by pump9918** [Team-Sopetit/Sopetit-Android#138]
## 🛠️ ISSUE
- QA 이슈 슈정

## 📑 To-Do
- [x] 뷰 페이저 좌우 삭제
- [x] xml 간격 figma랑 비교해서 다시 조정하기
- [x] 카드 엠티 이미지 placeholder 세팅
- [x] 행복루틴 목록 아이콘 placeholder 규격 재조정
- [x] 화면 전환 시 이전 스택 이미지 보이는 문제 해결
