### ISSUE TITLE
[qa] 데일리 루틴 2차 qa 이슈

### ISSUE THREAD

**Issue by minemi00** [Team-Sopetit/Sopetit-Android#151]
## 🛠️ ISSUE
최종 qa(이길..) 데일리 루틴 이슈 해결하기

## 📑 To-Do
- [ ] 세번째 라디오 버튼 위치 수정하기
- [ ] 카드 모양 맞추기
- [ ] 테마 로딩 빠르게 해결하기
