### ISSUE TITLE
[ui] 데일리/행복 루틴 뷰에서 추가 시, 토스트+바텀 시트

### ISSUE THREAD

**Issue by stellar-halo** [Team-Sopetit/Sopetit-Android#50]
## 🛠️ ISSUE
- 데일리/행복 루틴 뷰에서 추가 시, 토스트+바텀 시트 작업하기
- 스플래시 로고 변경하기

## 📑 To-Do
- [ ] 데일리 루틴 뷰에서 추가 시, 토스트 + 바텀 시트
- [ ] 행복 루틴 뷰 추가 시, 토스트 + 바텀 시트
- [x] 스플래시 로고 text, svg로 변환
