### ISSUE TITLE
[ui] Happy Routine - 엠티뷰 (xml)

### ISSUE THREAD

**Issue by pump9918** [Team-Sopetit/Sopetit-Android#6]
## 🛠️ ISSUE
- 엠티뷰 xml 작성

## 📑 To-Do
- [x] 사용자별 곰돌이 이미지 피그마 export
- [x] 행복루틴 empty 카드 생성
- [x] 말풍선 피그마 export
