### ISSUE TITLE
[FIX] 1차 QA 자잘한 이슈 해결 

### ISSUE THREAD

**Issue by emjayMJkim** [Team-Sopetit/Sopetit-Android#79]
## 🛠️ ISSUE
- 자잘한 이슈 해결 

## 📑 To-Do
- [x] 토스트 메시지 떠있는 시간 조정
- [x] 온보딩 뷰 루틴 리사이클러뷰 위치 조절
- [x] 배경화면 클릭시 hide keyboard
