### ISSUE TITLE
[ui] Daily Routine - 추가하기

### ISSUE THREAD

**Issue by minemi00** [Team-Sopetit/Sopetit-Android#8]
## 🛠️ ISSUE
- 데일리 루틴 추가하기 뷰

## 📑 To-Do
- [ ] 리사이클러뷰로 테마 만들기
- [ ] 구분선
- [ ] 뷰페이저 사용해서 루틴 카드만들기
- [ ] 인디케이터, 뷰페이저 양 옆 보이기
